server:
  servlet:
    context-path: /openapi/dev
  port: 8090

spring:
  config:
    activate.on-profile: ams-security
    name: ams-security-YAML
  application:
    name: ams-security
#  datasource:
#    url: jdbc:postgresql://ams.cx6suoeq6va5.eu-north-1.rds.amazonaws.com:5432/postgres
#    username: postgres
#    password: postgres
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    type: org.apache.tomcat.jdbc.pool.DataSource
#    tomcat:
#      max-wait: 20000
#      max-active: 300
#      max-idle: 10
#      min-idle: 5
#      initial-size: 2
#      test-on-connect: true
#      test-on-borrow: true
#      validation-query: SELECT 1 FROM DUAL
#      validation-query-timeout: 10
#      validation-interval: 15000
#      remove-abandoned: false
#      remove-abandoned-timeout: 30
#      jmx-enabled: true
#  jpa:
#    generate-ddl: false
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#        default_schema: fcr24

#  jackson:
#    serialization:
#      write-dates-as-timestamps: false

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [${spring.zipkin.service.name:${spring.application.name:-}},%X{traceId:-},%X{spanId:-}]
      [%t] %-5level %logger{36} - %msg%n'
  level:
    web: WARN
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: DEBUG
      springframework:
        web: TRACE
      apache.tomcat.jdbc.pool: debug

# App Properties
ams-security:
  jwt-config:
    secret: thisIsMyStrongSecretKeyThisIsMyStrongSecretKeyThisIsMyStrongSecretKeyThisIsMyStrongSecretKey
    expiration-ms: 6000000
    refresh-expiration-ms: 12000000

jasypt:
  encryptor:
    password: sdnk#sdjfk@

aes:
  KEY_SIZE: 128
  INTERACTION_COUNT: 1000
  SALT: fa91065ebff733b9fad5497f2b7dacdc
  IV: 465f899cae94b80c72411935556cb113
  PASSPHRASE: mypassphrase
